name: Deploy MoneyBizz
on:
    push:
        branches: [master]
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: test code
              uses: actions/checkout@v2
              uses: actions/setup-node@v2
              with:
                  node-version: "12"
              run: |
                  npm install
                  npm test
            - name: login
              uses: actions/heroku@master
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            - name: Deploy
              uses: actions/heroku@master
              run: git push heroku master
