name: Deploy MoneyBizz
on:
    push:
        branches: [master]
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - run: npm install
            - run: npm test
            - name: login
              uses: actions/heroku@master
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            - name: Deploy
              uses: actions/heroku@master
              run: git push heroku master
