name: Deploy MoneyBizz
on:
    push:
        branches: [master]
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: login
              uses: actions/heroku@master
              env:
                  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
